name: polaris-backend

services:
  db:
    container_name: db
    image: mongo:7
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ./db:/data
